config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  resources :products do
    resources :reviews
  end

  resources :order_items
  resource :cart, only: [:show] do
    resources :charges
  end

  resources :accounts, only: [:index, :update]
  resources :orders, only: [:index]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
    @rainchecked = current_raincheck
  end
end

app/views/carts/show.html.erb
<h1>Your Cart</h1>

<% if @cart.order_items.any? %>
  <ul id="cart-items">
    <% @cart.order_items.each do |item| %>
      <%= render "order_items/order_item", item: item %>
    <% end %>
  </ul>
  <p>Order Total: $<span id="cart-total"><%= @cart.price_total %></span></p>
  <%= link_to new_cart_charge_path do %>
    <button type="button" class="btn btn-default">Checkout</button>
  <% end %>
<% else %>
  <h3>You have no items in your cart.</h3>
<% end %>
<hr>
<h1>Rainchecked Books</h1>
<% if @rainchecked.order_items.any? %>
  <ul>
    <% @rainchecked.order_items.each do |item| %>
      <li id="order-item-<%= item.id %>">
        <%= link_to item.product.name, product_path(item.product) %>
        $<%= item.product.price %> each |
        <%= link_to "Add to cart", order_item_path(item), remote: true, data: { method: "patch" }  %> |
        <%= link_to "Remove", order_item_path(item), remote: true, data: { method: "delete" } %>
      </li>
    <% end %>
  </ul>
<% end %>