config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  resources :products do
    resources :reviews
  end

  resources :order_items
  resource :cart, only: [:show] do
    resources :charges
  end

  resources :accounts, only: [:index, :update]
  resources :orders, only: [:index]
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates_presence_of :name, :description, :quantity, :price, :author

  scope :alphabetical, -> { order(:name) }
  scope :featured, -> { where("featured = true") }
  scope :discounted, -> { where("discount > 0 AND discount_end >= ?", Date.today).order("discount_end ASC")}

  def low_stock?
    self.quantity <= 10 && self.quantity > 0
  end

  def has_discount?
    (self.discount && self.discount_end) && (self.discount_end >= Date.today)
  end

  def get_price(preferred=false)
    if self.has_discount?
      return self.price - (self.price * (self.discount / 100.0)).to_i
    elsif preferred
      return self.price - (self.price * 0.1).to_i
    end
    return self.price
  end

  def self.price_low_to_high(preferred=false)
    return Product.all.sort do |a,b|
      a.get_price(preferred) <=> b.get_price(preferred)
    end
  end

  def self.price_high_to_low(preferred=false)
    return Product.all.sort do |a,b|
      b.get_price(preferred) <=> a.get_price(preferred)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @featured = Product.featured
    @discounted = Product.discounted
    if current_user
      @preferred = current_user.account.preferred
    else
      @preferred = false
    end

    @sort_method = params[:sort_method] ? params[:sort_method] : "alphabetical"
    if (@sort_method == 'price_ascending')
      @products = Product.price_low_to_high(@preferred).paginate(:page => params[:page], :per_page => 10)
    elsif(@sort_method == 'price_descending')
      @products = Product.price_high_to_low(@preferred).paginate(:page => params[:page], :per_page => 10)
    else
      @products = Product.alphabetical.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def show
    @product = Product.find(params[:id])
    @order_item = OrderItem.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      respond_to do |format|
        format.html {
          flash[:notice] = "Product created!"
          redirect_to product_path(@product)
        }
        format.js
      end
    else
      flash[:alert] = @product.errors.full_messages
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @order_item = OrderItem.new
    if @product.update(product_params)
      respond_to do |format|
        format.html {
          flash[:notice] = "Product updated successfully."
          redirect_to product_path(@product)
        }
        format.js
      end
    else
      flash[:alert] = @product.errors.full_messages
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html {
        flash[:notice] = "Product has sucked into a black hole."
        redirect_to products_path
      }
      format.js
    end
  end

private
  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity, :author, :featured, :discount, :discount_end)
  end
end

app/views/products/_form.html.erb
<div id="product-edit-<%= @product.id %>" class="form product-details-panel">
  <%= form_for @product, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :quantity %>
        <%= f.number_field :quantity, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :discount %>
        <%= f.number_field :discount, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :discount_end %>
        <%= f.date_field :discount_end, class: 'form-control' %>
    </div>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="product" id="product-<%= product.id %>">
  <h3><%= link_to product.name, product_path(product), id: "show_product_#{product.id}", remote: true %></h3>
  <% if product.quantity < 1 %>
    <h5 class="text-danger">Sold Out!</h5>
  <% end %>
</div>

app/views/products/_products.html.erb
<% if @products.any? %>
  <% @products.each do |product| %>
    <%= render 'product', product: product %>
  <% end %>
<% else %>
  <h3>There are no saved books.</h3>
<% end %>

app/views/products/_show.html.erb
<div id="product-details-<%= @product.id %>" class="product-details-panel">

  <% if @product.featured %>
    <h5 class="text-success">Featured Title!</h5>
  <% end %>
  <h1 class="faux-link" id="hide_details_<%= @product.id %>" data-remote="true"><%= @product.name %></h1>
  <h4>By <%= @product.author %></h4>
  <% if @product.has_discount? %>
    <h3><del>$<%= @product.price %></del> <span class="text-success">$<%= @product.get_price %></span></h3>
    <h5 class="text-success">On sale until: <%= @product.discount_end.strftime("%B %-d, %Y") %></h5>
  <% elsif current_user && current_user.account.preferred %>
    <h3><del>$<%= @product.price %></del> <span class="text-success">$<%= @product.get_price(true) %></span></h3>
    <h5 class="text-success">Preferred customer discount </h5>
  <% else %>
    <h3>$<%= @product.price %></h3>
  <% end %>
  <% if @product.low_stock? %>
    <h5 class="text-danger">Low Stock! Only <%= @product.quantity %> remaining!</h5>
  <% end %>

  <% if @product.quantity > 0 %>
    <div class="user-product-options">
      <%= form_for @order_item, remote: true do |f| %>
        <%= f.hidden_field :product_id, value: @product.id %>
        <%= f.hidden_field :order_type, value: "Cart" %>
        <%= f.number_field :quantity, { value: 1, max: @product.quantity, min: 1, class: 'form-control quantity'} %>
        <%= f.submit "Add to cart", class: "btn btn-default" %>
      <% end %>

      <%= form_for @order_item, remote: true do |f| %>
        <%= f.hidden_field :product_id, value: @product.id %>
        <%= f.hidden_field :quantity, value: 1 %>
        <%= f.hidden_field :order_type, value: "Raincheck" %>
        <%= f.submit "Raincheck", class: "btn btn-default" %>
      <% end %>
    </div>
  <% else %>
    <h4 class="text-danger">Out of Stock!</h4>
  <% end %>
  <p><%= @product.description %></p>

  <% if current_user && current_user.admin? %>
    <hr>
    <p>
      <% if !@product.featured %>
        <%= link_to "Feature", product_path(product: { id: @product.id, featured: true}), id: "add_feature", remote: true, data: { method: "patch" } %> |
      <% else %>
        <%= link_to "End Feature", product_path(product: { id: @product.id, featured: false}), id: "remove_feature", remote: true, data: { method: "patch" } %> |
      <% end %>
      <%= link_to "Edit", edit_product_path(@product), id: "product-edit", remote: true %> |
      <%= link_to "Delete", product_path(@product), remote: true, data: {
                confirm: "This will shoot the book into a black hole. Are you sure?",
                method: "delete"
                } %>
    </p>
  <% end %>
  <h5><%= link_to "Hide Reviews", product_path(@product), class: "hidelink", id: "hide_reviews_#{@product.id}", remote: true %></h5>
  <h5><%= link_to "Show Reviews", product_reviews_path(@product), id: "show_reviews_#{@product.id}", remote: true %></h5>
  <%= render "reviews/index" %>
</div>

app/views/products/create.js.erb
$('#new_product').remove();
$('#new_product_link').show();
$('.all-books').prepend('<%= j render @product %>');

app/views/products/destroy.js.erb
$('#product-details-<%= @product.id %>').remove();

app/views/products/edit.html.erb
<h1>Edit Book</h1>

<%= render "form" %>

app/views/products/edit.js.erb
$('#product-details-<%= @product.id %>').after("<%= j render 'form' %>");
$('#product-details-<%= @product.id %>').remove();

app/views/products/index.html.erb
<div class="page-header">
  <h1>Unbelievable Books</h1>
</div>

<% if current_user && current_user.admin? %>
  <h4><%= link_to "Add a Book", new_product_path, id: "new_product_link", remote: true %></h4>
<% end %>

<div class="spotlight">
  <% if @featured.any? %>
    <div class="feature-wrapper">
      <h1>Featured</h1>
      <div class="featured-products">
        <% @featured.each do |product| %>
          <div class="product-feature" id="feature-<%= product.id %>">
            <h3><%= link_to product.name, product_path(product) %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @discounted.any? %>
    <div class="sale-wrapper">
      <h1>On Sale</h1>
      <% @discounted.each do |product| %>
        <div class="product-sale">
          <h3><%= link_to product.name, product_path(product) %></h3>
          <h5 class="text-success">On sale until: <%= product.discount_end.strftime("%B %-d, %Y") %></h5>
        </div>
      <% end %>
    </div>
  <% end %>  
</div>

<h1>All Books</h1>

<%= form_tag products_path, method: "get", id: "sort-form", remote: true  do %>
  <%= select_tag :sort_method, options_for_select([['Alphabetical', 'alphabetical'], ['Price (Low to high)', 'price_ascending'], ['Price (High to low)', 'price_descending']], @sort_method), remote: true %>
  <%= submit_tag "Sort", id: "sort-method-button", class: "btn btn-default" %>
<% end %>

<div class="all-books">
  <%= render 'products' %>
</div>

<div class="page-wrapper">
  <%= will_paginate @products %>
</div>

app/views/products/index.js.erb
$('.all-books').html('<%= j render "products" %>');
$('.page-wrapper').html('<%= j will_paginate @products %>');
$('.pagination > a').attr('data-remote', 'true');

app/views/products/new.js.erb
$('#new_product_link').hide().after('<%= j render "form" %>');

app/views/products/show.html.erb
<%= render "show" %>

app/views/products/show.js.erb
$('#product-<%= @product.id %>').after('<%= j render("show") %>');
$('#product-<%= @product.id %>').remove();
$('#hide_details_<%= @product.id %>').click(function() {
  $('#product-details-<%= @product.id %>').before('<%= j render @product %>')
  $('#product-details-<%= @product.id %>').remove();
});

app/views/products/update.js.erb
$('#product-details-<%= @product.id %>').after("<%= j render 'show' %>");
$('#product-details-<%= @product.id %>').remove();
$('#product-edit-<%= @product.id %>').before("<%= j render 'show' %>");
$('#product-edit-<%= @product.id %>').remove();
$('#hide_details_<%= @product.id %>').click(function() {
  $('#product-details-<%= @product.id %>').before('<%= j render @product %>')
  $('#product-details-<%= @product.id %>').remove();
});

<% if @product.featured %>
  $('#feature-<%= @product.id %>').remove();
  $('.featured-products').prepend('<div class="product-feature" id="feature-<%= @product.id %>"><h3><%= link_to @product.name, product_path(@product) %></h3></div>');
<% else %>
  $('#feature-<%= @product.id %>').remove();
<% end %>