config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  resources :products do
    resources :reviews
  end

  resources :order_items
  resource :cart, only: [:show] do
    resources :charges
  end

  resources :accounts, only: [:index, :update]
  resources :orders, only: [:index]
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @cart = current_cart
    @quotes = Currency.get_exchange_rates
    @tax_total = current_cart.total_with_tax
  end

  def create
    @cart = current_cart
    # Check if everything in cart is valid
    if @cart.confirm_items
      # Amount in cents
      @amount = (@cart.total_with_tax * 100).to_i

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )
      # Update products ordered to lower quantity appropriately
      @cart.remove_inventory
      # Change cart order from cart to placed.
      @cart.update(status: "Placed", final_price: @amount)
      OrderMailer.order_confirmation(@cart).deliver
    else
      flash[:alert] = @cart.errors.full_messages
      flash[:alert].push("You have not been charged. Please update your cart.")
      redirect_to new_cart_charge_path
    end
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_cart_charge_path
  end
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$<%= (@amount / 100.0)  %></strong>!</h2>
<h3>You can review this purchase in your <%= link_to "Order History", orders_path %>.</h3>

app/views/charges/new.html.erb
<h1>Checkout</h1>

<% if @cart.order_items.any? %>
  <ul>
    <% @cart.order_items.each do |item| %>
      <li class="order-item">
        <%= item.quantity %>
        <%= link_to item.product.name, product_path(item.product) %>
        $<%= item.reserved_price %> each |
        $<%= item.reserved_price * item.quantity %> total
      </li>
    <% end %>
  </ul>

  <%= form_tag cart_charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Order Total: $<%= @cart.price_total %></span>
      </label>
      <p>
        <strong>Other Currencies:</strong>
        <% @quotes.each do |currency, rate| %>
          <span><strong><%= currency[3..-1] %>:</strong> <%= '%.2f' % (rate * @cart.price_total) %> </span>
        <% end %>
      </p>
      <hr>
      <label class="amount">
        <span>With Tax: $<%= '%.2f' % @tax_total %></span>
      </label>
      <p>
        <strong>Other Currencies:</strong>
        <% @quotes.each do |currency, rate| %>
          <span><strong><%= currency[3..-1] %>:</strong> <%= '%.2f' % (rate * @tax_total) %> </span>
        <% end %>
      </p>
    </article>

    <%= link_to cart_path do %>
      <button type="button" class="btn btn-default">Back to Cart</button>
    <% end %>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="<%= @tax_total * 100 %>"
            data-locale="auto"></script>
  <% end %>
<% end %>