config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  resources :products do
    resources :reviews
  end

  resources :order_items
  resource :cart, only: [:show] do
    resources :charges
  end

  resources :accounts, only: [:index, :update]
  resources :orders, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnbelievableBooks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
           <%= link_to "Unbelievable Books", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "All Books", products_path %></li>
          <% if current_user && current_user.admin? %>
            <li><%= link_to "Accounts", accounts_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li id="username"><%= link_to "Signed in as #{current_user.email}" %></li>
            <% if current_cart.order_items.any? %>
              <li><%= link_to "Cart: ( #{current_cart.book_count} Books |  $#{current_cart.price_total} )", cart_path, id: "cart_link" %></li>
            <% else %>
              <li><%= link_to "Cart", cart_path, id: "cart_link" %></li>
            <% end %>
            <li><%= link_to "Orders", orders_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container contents">
      <% if flash[:notice] != nil %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] != nil %>
        <div class="alert alert-danger">
          <% if flash[:alert].class == Array %>
            <p><strong>Something went wrong!</strong></p>
            <ul>
              <% flash[:alert].each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% else %>
            <%= flash[:alert] %>
          <% end %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>